### ISSUE TITLE
BUG: studio VS studios 

### ISSUE THREAD

**Issue by zosky** [XBMC-Addons/plugin.library.node.editor#4]
ACTION: add custom video nodes with a rule for studio ... it does not work
BUG: the node editor is making <rule field="studios" while a smart playList does <rule field="studio" 
WORKAROUND: editing the new-node.xml (making studio*s* singular) allows me to browse the new-node ... but the editor can not edit it any more

**Comment by ronie** [comment]
sorry, forgot about this one.
i've fixed it right after your bugreport, but forgot to push my fix for it.

thanx for the report!

https://github.com/XBMC-Addons/plugin.library.node.editor/commit/74a2d0d5fb198026bd08c15d3712075da93b4487
